In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


numpy-기초


In [4]:
arr1=np.array([1,2,3]) #1차원 배열 
arr2=np.array([[1,2,3],[1,2,3]]) # 2차원 배열 

arr1
arr2

array([[1, 2, 3],
       [1, 2, 3]])

arr1=np.array([1,2,3]) #1차원 배열 
arr2=np.array([[1,2,3],[1,2,3]]) # 2차원 배열

In [6]:
arr1.shape #(3,)
arr1.

(3,)

In [5]:
arr2.shape #(2,3) => 2행 3열인 2차원 배열 
arr2.ndim #2 => 2차원 

2

In [10]:
list3=[[[1,2,3]]] # list

arr3=np.array(list3) #np.array

arr3
arr3.ndim #3 =>3차원
arr3.dtype
arr3.shape

(1, 1, 3)

In [8]:
list2=[1,2,'c']

arr4=np.array(list2)
arr4

array(['1', '2', 'c'], dtype='<U11')

In [9]:
arr=np.array(["1","2","3","4","5"])
arr.dtype

final_arr=arr.astype('int64')
final_arr.dtype

dtype('int64')

ndarray
* arange
* zeros
* ones

In [15]:
#arange()
arr=np.arange(10)

#slicing
arr[0:6]

#indexing
arr[-1]

arr>5

arr[arr>5]


array([6, 7, 8, 9])

In [16]:
#zeros

np.zeros([3,2],dtype='int32')


array([[0, 0],
       [0, 0],
       [0, 0]])

In [17]:
# ones
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

reshape()-차원과 크기 변경 

In [21]:
arr1=np.arange(10)

print(arr1)

arr2=arr1.reshape(2,5)

print(arr2)

arr3=arr1.reshape(5,2)
print(arr3)

#cannot reshape array of size 10 into shape (3,4)
arr4=arr1.reshape(3,4)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (3,4)

In [22]:
arr=np.arange(8)
arr

arr2=arr.reshape(-1,4)
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5) # 5열에 맞춰서 -> 행을 만들어줘(알아서 )
print(array2)
print(array2.shape)

array3 = array1.reshape(5, -1) # 5행에 맞춰서 알아서 맞춰줘
print(array3)
print(array3.shape)

array4 = array1.reshape(2, -1) # 2행에 맞춰서 알아서 만들어줘
array4


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
(5, 2)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

인덱싱 , 슬라이싱 

In [24]:
arr=np.arange(1,10)

arr[0]
arr[0:5]
arr[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr=np.arange(1,10)

arr2=arr.reshape(3,3)
print(arr2)

arr2[1,1] #5
arr2[2,2] #9
arr2[2][2]

arr2[0,0:3] #[1,2,3]
arr2[1,0:3] #[4,5,6]

#[3,6,9]
arr2[:,2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

* boolean indexing

In [31]:
arr=np.arange(1,10)

arr>5

array([False, False, False, False, False,  True,  True,  True,  True])

* 정렬

In [34]:
arr=np.array([10,30,5,1,100])

#오름차순
arr_sorted=np.sort(arr)
arr_sorted

#내림차순
arr_sorted[::-1]

array([100,  30,  10,   5,   1])

In [36]:
arr_countries=np.array(['kor','usa','china'])
arr_sorted=np.sort(arr_countries)
arr_sorted

array(['china', 'kor', 'usa'], dtype='<U5')

## 행렬의 연산

In [39]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

print(arr1)
print(arr2)

arr_add=np.add(arr1,arr2)
print(arr_add)

arr_mul=np.multiply(arr1,arr2)
print(arr_mul)

arr_dot=np.dot(arr1,arr2)
print(arr_dot)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [46]:
# 2차원 배열에서 행렬의 각 행의 평균을 계산하는 코드를 작성하세요
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.ndim

for i in arr:
    print(np.mean(i))

2.0
5.0
8.0


In [47]:
# 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요

arr=np.array([1,2,3,4,5,6])

for i in range(0,len(arr),2):
    print(arr[i])

1
3
5


In [ ]:
# Q2. 1차원 배열에서 짝수 인덱스의 값을 출력하는 코드를 작성하세요.
# 짝수값을 출력을 한다. / 해당 값들의 인덱스 값을 가져온다.

arr = np.array([1, 2, 3, 4, 5, 6])

even_indexes = np.arange(0, arr.size, 2)
even_indexes

arr[even_indexes]


In [48]:
# 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.diag(arr)) # diag

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [50]:
# 2차원 배열에서 각열의 표준편차를 계산하는 코드를 작성하세요 
# 표준 편자 ==> np.std()

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
np.std(arr,axis=0) # 행의 표준편차 
np.std(arr,axis=1) # 열의 표준편차

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


2.581988897471611